version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: tea19
            MYSQL_DATABASE: tea19
            MYSQL_USER: tea19
            MYSQL_PASSWORD: tea19
        ports:
            - "3306:3306"